"""Weather service wrapper used by the backend API layer."""

from typing import Any

from reader import ShortWeatherAPIReader


def get_weather(date: str, time: str, place: str) -> dict[str, Any]:
    """Return short-range weather data for the given date, time, and place.

    Args:
        date: Target date in `YYYY.MM.DD` or `YYYY-MM-DD` format.
        time: Target time in `HH:MM` format.
        place: Address or place name that Kakao address search can resolve.

    Returns:
        Weather summary dictionary generated by `ShortWeatherAPIReader`.
    """
    # Keep API-facing code independent from the concrete reader class.
    reader = ShortWeatherAPIReader()
    return reader.get(date, time, place)
