"""Weather service wrapper used by the backend API layer."""

import logging
import time
from typing import Any

from backend.reader import ShortWeatherAPIReader

logger = logging.getLogger("backend.weather")


def get_weather(date: str, time: str, place: str) -> dict[str, Any]:
    """Return short-range weather data for the given date, time, and place.

    Args:
        date: Target date in `YYYY.MM.DD` or `YYYY-MM-DD` format.
        time: Target time in `HH:MM` format.
        place: Address or place name that Kakao address search can resolve.

    Returns:
        Weather summary dictionary generated by `ShortWeatherAPIReader`.
    """
    # Keep API-facing code independent from the concrete reader class.
    logger.info("weather.get_start date=%s time=%s place=%s", date, time, place)
    start = time.perf_counter()
    reader = ShortWeatherAPIReader()
    try:
        weather = reader.get(date, time, place)
    except Exception:
        logger.exception("weather.get_failed elapsed_seconds=%.3f", time.perf_counter() - start)
        raise
    logger.info(
        "weather.get_done source=%s condition=%s elapsed_seconds=%.3f",
        weather.get("source"),
        weather.get("condition"),
        time.perf_counter() - start,
    )
    return weather
